CREATE MULTISET TABLE DL_ESI_PROD.CPT_RVU_CMS ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      Yr INTEGER,
      CPT VARCHAR(50) CHARACTER SET LATIN CASESPECIFIC,
      Unit_RVU DECIMAL(38,6),
      Start_Date TIMESTAMP(6),
      End_Date TIMESTAMP(6),
      insert_dttm TIMESTAMP(6))
UNIQUE PRIMARY INDEX ( CPT ,Start_Date ,End_Date );